# GitHub Dependabot Configuration
#
# Dependabot can maintain your repository's dependencies automatically.
#
# Documentation:
# - https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# - https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2

updates:
  - package-ecosystem: pip
    directory: /
    groups:
      development-dependencies:
        dependency-type: development
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore:"
    labels:
      - dependencies
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    groups:
      production-dependencies:
        dependency-type: production
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore:"
    labels:
      - dependencies
    open-pull-requests-limit: 5
